# fly.toml app configuration file generated for shock-jb on 2024-10-11T08:45:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shock-jb'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
